import React, { useEffect, useMemo, useState } from 'react';
import { Download, Info, Sparkles } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import api from '../utils/api';
import { useAuth } from '../hooks/useAuth';
import { formatPrice } from '../lib/currency';
import AsyncBoundary from './AsyncBoundary';
import '../styles/AnalyticsDashboard.css';

const metrics = [
  ['Total Enrollments', 'Number of students enrolled in this class.', (data) => data.totalEnrollments ?? 0],
  ['Total Revenue', 'Gross revenue generated by this class.', (data, currency) => formatPrice((Number(data.totalRevenue) || 0) * 100, currency)],
  ['Average Rating', 'Average rating from published student reviews.', (data) => data.avgRating == null ? '—' : Number(data.avgRating).toFixed(1)],
  ['Completion Rate', 'Students who completed the class access period.', (data) => data.completionRate == null ? '—' : `${data.completionRate}%`],
];

function EmptyTrend() {
  return <div className="analytics-trend-empty"><svg viewBox="0 0 320 120" aria-hidden="true"><path d="M8 104H312M8 104V12" /><path d="M8 82H312M8 52H312M8 22H312" /></svg><span>No data yet — trends appear once students enroll</span></div>;
}

function TrendChart({ data, dataKey, currency, formatValue }) {
  if (!Array.isArray(data) || data.length === 0) return <EmptyTrend />;
  return <div className="analytics-trend-chart"><ResponsiveContainer width="100%" height={220}><AreaChart data={data} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}><defs><linearGradient id={`trend-${dataKey}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4f46e5" stopOpacity=".2" /><stop offset="100%" stopColor="#4f46e5" stopOpacity="0" /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e2e8f0" strokeDasharray="3 4" /><XAxis dataKey="date" hide /><YAxis hide tickFormatter={formatValue} /><Tooltip formatter={(value) => formatValue(value)} contentStyle={{ borderRadius: 8, border: '1px solid #e2e8f0' }} /><Area type="monotone" dataKey={dataKey} stroke="#475569" strokeWidth={2} fill={`url(#trend-${dataKey})`} dot={{ r: 3, fill: '#4f46e5', strokeWidth: 0 }} activeDot={{ r: 5, fill: '#4f46e5' }} /></AreaChart></ResponsiveContainer></div>;
}

export default function AnalyticsDashboard({ classId }) {
  const { user } = useAuth();
  const [analytics, setAnalytics] = useState(null);
  const [loading, setLoading] = useState(true);
  const [period, setPeriod] = useState('weekly');
  const [error, setError] = useState(false);
  const currency = user?.preferredCurrency || 'USD';

  const fetchAnalytics = async () => {
    try {
      setLoading(true);
      setError(false);
      const { data } = await api.get(`/analytics/class/${classId}?period=${period}`);
      setAnalytics(data);
    } catch (requestError) {
      console.error('Failed to fetch analytics', requestError);
      setError(true);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchAnalytics(); }, [classId, period]);

  const exportReport = () => {
    const rows = [
      ['Metric', 'Value'],
      ...metrics.map(([label, , getter]) => [label, getter(analytics, currency)]),
      [],
      ['Revenue trend', 'Date', 'Revenue'],
      ...(analytics?.revenueData || []).map((point) => [point.date, point.amount]),
      [],
      ['Enrollment trend', 'Date', 'Enrollments'],
      ...(analytics?.enrollmentData || []).map((point) => [point.date, point.count]),
    ];
    const csv = rows.map((row) => row.map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
    const link = document.createElement('a');
    link.href = url;
    link.download = 'class-analytics.csv';
    link.click();
    URL.revokeObjectURL(url);
  };

  const enrollmentData = useMemo(() => (analytics?.enrollmentData || []).map((point) => ({ ...point, enrollments: point.count })), [analytics]);

  if (loading || error || !analytics) return <AsyncBoundary loading={loading} error={error} empty={!analytics && !loading && !error} onRetry={fetchAnalytics} loadingVariant="block" emptyMessage="Analytics will appear after your class has activity." />;

  return <div className="analytics-dashboard">
    <div className="analytics-page-header"><div><p className="eyebrow">Class performance</p><h1>Class Analytics</h1><p className="page-subtitle">Understand class activity and make every session better.</p></div><button type="button" className="analytics-export" onClick={exportReport}><Download size={16} /> Export Report</button></div>
    <section className="analytics-section"><div className="analytics-section-header"><h2>Performance overview</h2><label>Range <select value={period} onChange={(event) => setPeriod(event.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label></div><div className="metrics-grid">{metrics.map(([label, help, getter]) => <div className="metric-card" key={label}><div className="metric-label">{label}<span title={help}><Info size={14} /></span></div><div className="metric-value">{getter(analytics, currency)}</div></div>)}</div></section>
    <section className="analytics-trends"><div className="analytics-section-header"><h2>Trends</h2><span className="analytics-section-note">{period}</span></div><div className="charts-container"><article className="chart"><h3>Revenue Trend</h3><TrendChart data={analytics.revenueData} dataKey="amount" formatValue={(value) => formatPrice(Number(value || 0) * 100, currency)} /></article><article className="chart"><h3>Enrollment Trend</h3><TrendChart data={enrollmentData} dataKey="enrollments" formatValue={(value) => `${value || 0} students`} /></article></div></section>
    <section className="engagement-section"><div className="analytics-section-header"><h2>Engagement Metrics</h2><span className="analytics-section-note">Student activity</span></div><div className="engagement-metrics">{[['Avg. Session Duration', 'Average time students spend in a session.', analytics.avgSessionDuration ? `${analytics.avgSessionDuration} min` : '—'], ['Attendance Rate', 'Attended sessions divided by sessions available.', analytics.attendanceRate ? `${analytics.attendanceRate}%` : '—'], ['Chat Activity', 'Messages sent by students during class sessions.', analytics.totalMessages ? `${analytics.totalMessages} messages` : '—'], ['Retention Rate', 'Students who return after their first session.', analytics.retentionRate ? `${analytics.retentionRate}%` : '—']].map(([label, help, value]) => <div className="engagement-item" key={label}><div className="metric-label">{label}<span title={help}><Info size={14} /></span></div><strong>{value}</strong></div>)}</div></section>
    <section className="recommendations-section"><div className="analytics-section-header"><h2>AI Recommendations</h2><Sparkles size={18} /></div>{analytics.recommendations?.length ? <div className="recommendations-list">{analytics.recommendations.map((recommendation, index) => <article className="recommendation-item" key={index}><span className="recommendation-badge">Insight</span><p>{recommendation}</p></article>)}</div> : <div className="analytics-empty"><Sparkles size={24} /><p>No recommendations yet — they appear as your classes gather data</p></div>}</section>
  </div>;
}
