import axios from 'axios';

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const OPENAI_API_URL = 'https://api.openai.com/v1';

// Mock implementation for Phase 2 development
// Replace with actual OpenAI calls when API key is configured

export const transcribeAudio = async (audioUrl) => {
  try {
    if (!OPENAI_API_KEY) {
      console.warn('OpenAI API key not configured. Using mock transcription.');
      return 'This is a mock transcription. The actual transcription would be generated by OpenAI Whisper API.';
    }

    // Actual implementation would use OpenAI Whisper API
    // For now, return mock data
    return 'Welcome to today\'s class. Today we will cover the fundamentals of the topic. Let\'s start with an overview...';
  } catch (error) {
    console.error('Error transcribing audio:', error);
    return 'Transcription failed. Please try again.';
  }
};

export const summarizeContent = async (transcript) => {
  try {
    if (!OPENAI_API_KEY) {
      console.warn('OpenAI API key not configured. Using mock summary.');
      return 'This session covered the main concepts and provided practical examples.';
    }

    // Call OpenAI API for summarization
    const response = await axios.post(
      `${OPENAI_API_URL}/chat/completions`,
      {
        model: 'gpt-4',
        messages: [
          {
            role: 'system',
            content: 'You are an expert at summarizing educational content. Provide a concise 2-3 sentence summary.',
          },
          {
            role: 'user',
            content: `Summarize this lecture transcript:\n\n${transcript}`,
          },
        ],
        temperature: 0.7,
        max_tokens: 150,
      },
      {
        headers: {
          Authorization: `Bearer ${OPENAI_API_KEY}`,
          'Content-Type': 'application/json',
        },
      }
    );

    return response.data.choices[0].message.content;
  } catch (error) {
    console.error('Error summarizing content:', error);
    return 'Unable to generate summary at this time.';
  }
};

export const generateChapters = async (transcript) => {
  try {
    if (!OPENAI_API_KEY) {
      return [
        { timestamp: 0, title: 'Introduction' },
        { timestamp: 600, title: 'Main Content' },
        { timestamp: 1200, title: 'Examples & Discussion' },
        { timestamp: 1800, title: 'Conclusion' },
      ];
    }

    const response = await axios.post(
      `${OPENAI_API_URL}/chat/completions`,
      {
        model: 'gpt-4',
        messages: [
          {
            role: 'system',
            content:
              'You are an expert at structuring educational content. Generate chapter markers as JSON array with timestamp (in seconds) and title.',
          },
          {
            role: 'user',
            content: `Create chapter markers for this transcript. Return valid JSON only:\n\n${transcript}`,
          },
        ],
        temperature: 0.7,
        max_tokens: 300,
      },
      {
        headers: {
          Authorization: `Bearer ${OPENAI_API_KEY}`,
          'Content-Type': 'application/json',
        },
      }
    );

    try {
      return JSON.parse(response.data.choices[0].message.content);
    } catch {
      return [];
    }
  } catch (error) {
    console.error('Error generating chapters:', error);
    return [];
  }
};

export const moderateContent = async (content) => {
  try {
    if (!OPENAI_API_KEY) {
      return { isSafe: true, flaggedCategories: [] };
    }

    const response = await axios.post(
      `${OPENAI_API_URL}/moderations`,
      {
        input: content,
      },
      {
        headers: {
          Authorization: `Bearer ${OPENAI_API_KEY}`,
          'Content-Type': 'application/json',
        },
      }
    );

    const result = response.data.results[0];

    return {
      isSafe: !result.flagged,
      flaggedCategories: Object.keys(result.categories).filter(cat => result.categories[cat]),
      scores: result.category_scores,
    };
  } catch (error) {
    console.error('Error moderating content:', error);
    return { isSafe: true, flaggedCategories: [] };
  }
};

export const generateQuiz = async (content, questionCount = 3) => {
  try {
    if (!OPENAI_API_KEY) {
      return [
        {
          question: 'What was the main topic discussed?',
          options: ['Option A', 'Option B', 'Option C', 'Option D'],
          correctAnswer: 0,
        },
      ];
    }

    const response = await axios.post(
      `${OPENAI_API_URL}/chat/completions`,
      {
        model: 'gpt-4',
        messages: [
          {
            role: 'system',
            content: `Generate ${questionCount} multiple choice quiz questions based on the content. Return valid JSON array.`,
          },
          {
            role: 'user',
            content: `Content:\n\n${content}`,
          },
        ],
        temperature: 0.7,
        max_tokens: 500,
      },
      {
        headers: {
          Authorization: `Bearer ${OPENAI_API_KEY}`,
          'Content-Type': 'application/json',
        },
      }
    );

    try {
      return JSON.parse(response.data.choices[0].message.content);
    } catch {
      return [];
    }
  } catch (error) {
    console.error('Error generating quiz:', error);
    return [];
  }
};

export const detectLanguage = async (text) => {
  try {
    // This is a simple language detection
    // For production, use a dedicated library like 'detect-language' or OpenAI
    const languages = {
      english: /hello|world|good|morning/i,
      spanish: /hola|buenos|días/i,
      french: /bonjour|salut/i,
      chinese: /你好|早上好/,
    };

    for (const [lang, pattern] of Object.entries(languages)) {
      if (pattern.test(text)) {
        return lang;
      }
    }

    return 'english'; // Default
  } catch (error) {
    console.error('Error detecting language:', error);
    return 'english';
  }
};
